name: CI

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  CI:
    name: Run CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name : Check style code
        run : |
          sudo apt-get install -y cppcheck
          cppcheck --enable=warning,style,performance,portability source/ include/
          sudo apt-get install python3-pip

      - name : Building
        run : |
          mkdir cmake-build-debug
          cd cmake-build-debug
          sudo apt-get install -y libgtest-dev
          python3 ../tests/generator/generator.py
          cmake ..
          make
          cd ..

      - name: Unit-tests one-thread
        run: |
          cd cmake-build-debug
          ./test_one_thread.out
          cd ..

      - name: Unit-tests multi-thread
        run: |
          cd cmake-build-debug
          ./test_multi_thread.out
          cd ..

      - name: Coverage test multi_thread
        run: |
#          sudo apt-get install lcov
#          mkdir coverage_one_th && cd coverage_one_th
#          gcov ../build/CMakeFiles/lib_matrix_one_thread.dir/project/src/matrix_one_thread.c.gcno
#          cp -r ../build/CMakeFiles/lib_matrix_one_thread.dir/ .
#          cd ..
#          lcov --capture --directory coverage_one_th/ --output-file matrix_one_thread.info
#          genhtml matrix_one_thread.info --output-directory coverage_one_th-report/

          sudo apt-get install lcov
          mkdir coverage_one_thread && cd coverage_one_thread
#          gcov ../build/CMakeFiles/lib_matrix_one_thread.dir/project/src/matrix_one_thread.c.gcno
#          cp -r ../build/CMakeFiles/lib_matrix_one_thread.dir/ .
          gcov ../cmake-build-debug/CMakeFiles/lib_multi_thread.dir/source/multi_thread.c.gcno
          cp -r ../cmake-build-debug/CMakeFiles/lib_multi_thread.dir/ .
          cd ..
          lcov --capture --directory coverage_one_thread/ --output-file multi_thread.info
          genhtml multi_thread.info --output-directory coverage_one_thread-report/


#          sudo apt-get install lcov
#          cd cmake-build-debug
#          ./test_multi_thread.out
#          cd ..
#          mkdir coverage && cd coverage
#          gcov ../cmake-build-debug/CMakeFiles/lib_multi_thread.dir/source/multi_thread.c.gcno
#          cp -r ../cmake-build-debug/CMakeFiles/lib_multi_thread.dir/ .
#          cd ..
#          lcov --capture --directory coverage/ --output-file multi_thread.info
#          genhtml multi_thread.info --output-directory coverage-report/

      - name: Coverage test one_thread
        run: |
          sudo apt-get install lcov
          cd cmake-build-debug
          ./test_one_thread.out
          cd ..
          mkdir coverage && cd coverage
          gcov ../cmake-build-debug/CMakeFiles/lib_one_thread.dir/source/one_thread.c.gcno
          cp -r ../cmake-build-debug/CMakeFiles/lib_one_thread.dir/ .
          cd ..
          lcov --capture --directory coverage/ --output-file one_thread.info
          genhtml one_thread.info --output-directory coverage-report/

      - name: Archive coverage test results
        uses: actions/upload-artifact@v2
        with:
          name: Coverage test
          path: coverage-report/

      - name: Valgrind test
        run: |
          sudo apt-get install -y valgrind
          mkdir valgrid-output
          valgrind --leak-check=full --tool=memcheck --show-leak-kinds=all --log-file=valgrid-output/report -q ./test_multi_thread.out
          valgrind --leak-check=full --tool=memcheck --show-leak-kinds=all --log-file=valgrid-output/report -q ./test_one_thread.out

      - name: Archive valgrind test results
        uses: actions/upload-artifact@v2
        with:
          name: Valgrind test
          path: valgrid-output/